/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.naming.Binding;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import java.awt.Component;
import javax.swing.JMenuItem;

/**
 *
 * @author Alizai
 */
public class AddContact extends javax.swing.JFrame {

    /**
     * Creates new form SeProject3
     */
    public AddContact() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        Mobile = new javax.swing.JTextField();
        Fax = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        AltEmail = new javax.swing.JTextField();
        ZipCode = new javax.swing.JTextField();
        StrNo = new javax.swing.JTextField();
        AppNo = new javax.swing.JTextField();
        StrName = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Year = new javax.swing.JComboBox();
        Month = new javax.swing.JComboBox();
        Day = new javax.swing.JComboBox();
        Cancel = new javax.swing.JButton();
        Cancel.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		System.exit(0);
        	}
        });
        Country = new javax.swing.JComboBox();
        City = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        Male = new javax.swing.JCheckBox();
        Female = new javax.swing.JCheckBox();
        AddInfo = new javax.swing.JTextField();
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        AddContact = new javax.swing.JMenuItem();
        EditContact = new javax.swing.JMenuItem();
        ManageContact = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Exit.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		System.exit(0);
        		
        	}
        });
        Edit = new javax.swing.JMenu();
        Undo = new javax.swing.JMenuItem();
        Redo = new javax.swing.JMenuItem();
        Copy = new JMenuItem();
        Cut = new javax.swing.JMenuItem();
        Past = new javax.swing.JMenuItem();
        Perference = new javax.swing.JMenuItem();
        View = new javax.swing.JMenu();
        SortA = new javax.swing.JMenuItem();
        SortZ = new javax.swing.JMenuItem();
        ZoomIn = new javax.swing.JMenuItem();
        ZoomOut = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        Mannul = new javax.swing.JMenuItem();
        Video = new javax.swing.JMenuItem();
        Version = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Contact ");
        

        panel1.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );

        jLabel1.setText("Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Date of Birt");

        jLabel4.setText("Phone #");

        jLabel5.setText("Mobile #");

        jLabel6.setText("Fax #");

        jLabel7.setText("Email Add");

        jLabel8.setText("Alt Email Add");

        jLabel9.setText("Country");

        jLabel10.setText("City ");

        jLabel11.setText("Zip Code");

        jLabel12.setText("Street No");

        jLabel13.setText("Apartment No");

        jLabel14.setText("Street Name");

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        Save.setText("Save Contact");

        Year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012" }));

      
        Month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " ", " " }));

        Day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Cancel.setText("Cancel ");

        Country.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        City.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Sex");

        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        Female.setText("Female");

        AddInfo.setText("Additional information ");

        File.setText("File");

        AddContact.setText("Add Contact ");
        File.add(AddContact);

        EditContact.setText("Edit Contact");
        File.add(EditContact);

        ManageContact.setText("Manage Contacts ");
        File.add(ManageContact);

        Exit.setText("Exit");
        File.add(Exit);

        MenuBar.add(File);

        Edit.setText("Edit");

        Undo.setText("Undo ");
        Edit.add(Undo);

        Redo.setText("redo");
        Edit.add(Redo);

        Copy.setSelected(true);
        Copy.setText("Copy ");
        Edit.add(Copy);

        Cut.setText("Cut");
        Edit.add(Cut);

        Past.setText("Past");
        Edit.add(Past);

        Perference.setText("Perference ");
        Edit.add(Perference);

        MenuBar.add(Edit);

        View.setText("View");

        SortA.setText("Sort A-Z");
        SortA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        View.add(SortA);

        SortZ.setText("Sort Z-A");
        View.add(SortZ);

        ZoomIn.setText("Zoom in +");
        View.add(ZoomIn);

        ZoomOut.setText("Zoom out -");
        View.add(ZoomOut);

        MenuBar.add(View);

        Help.setText("Help");

        Mannul.setText("Mannul ");
        Help.add(Mannul);

        Video.setText("Video Demo ");
        Help.add(Video);

        Version.setText("Version Info ");
        Help.add(Version);

        MenuBar.add(Help);

        setJMenuBar(MenuBar);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(40)
        					.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        							.addGroup(groupLayout.createSequentialGroup()
        								.addGap(41)
        								.addComponent(jLabel1))
        							.addGroup(groupLayout.createSequentialGroup()
        								.addGap(6)
        								.addComponent(jLabel2))
        							.addComponent(jLabel3))
        						.addComponent(jLabel15))
        					.addGap(18)
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(Name, GroupLayout.PREFERRED_SIZE, 191, GroupLayout.PREFERRED_SIZE)
        						.addComponent(LastName, GroupLayout.PREFERRED_SIZE, 191, GroupLayout.PREFERRED_SIZE)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addComponent(Year, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(Month, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(Day, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addGroup(groupLayout.createSequentialGroup()
        							.addComponent(Male)
        							.addGap(56)
        							.addComponent(Female)))
        					.addGap(30)
        					.addComponent(panel1, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(60)
        					.addComponent(jLabel4)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(Phone, GroupLayout.PREFERRED_SIZE, 199, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(65)
        					.addComponent(jLabel9)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(Country, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(34)
        					.addComponent(jLabel10)
        					.addGap(12)
        					.addComponent(City, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(29)
        					.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(jLabel12)
        								.addComponent(jLabel13)
        								.addComponent(jLabel11))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(ZipCode, GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        								.addComponent(StrNo, GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        								.addComponent(AppNo))
        							.addGap(17))
        						.addGroup(groupLayout.createSequentialGroup()
        							.addComponent(jLabel14)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(StrName, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(AddInfo, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
        					.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(28)
        							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        								.addGroup(groupLayout.createSequentialGroup()
        									.addGap(23)
        									.addComponent(jLabel7))
        								.addComponent(jLabel8))
        							.addGap(2)
        							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        								.addGroup(groupLayout.createSequentialGroup()
        									.addComponent(Email, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
        									.addComponent(Cancel, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE))
        								.addGroup(groupLayout.createSequentialGroup()
        									.addComponent(AltEmail, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED, 186, Short.MAX_VALUE))))
        						.addGroup(Alignment.LEADING, groupLayout.createSequentialGroup()
        							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        								.addGroup(groupLayout.createSequentialGroup()
        									.addGap(58)
        									.addComponent(jLabel5)
        									.addGap(2)
        									.addComponent(Mobile, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE))
        								.addGroup(groupLayout.createSequentialGroup()
        									.addGap(81)
        									.addComponent(jLabel6)
        									.addGap(2)
        									.addComponent(Fax, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)))
        							.addPreferredGap(ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
        							.addComponent(Save)))
        					.addGap(22)))
        			.addContainerGap())
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(21)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(37)
        							.addComponent(jLabel1)
        							.addGap(24)
        							.addComponent(jLabel2)
        							.addGap(23)
        							.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jLabel3)
        								.addComponent(Year, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(Month, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(Day, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(35)
        							.addComponent(Name, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(LastName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(60)
        							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        								.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        									.addComponent(Male)
        									.addComponent(jLabel15))
        								.addComponent(Female))))
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(29)
        							.addComponent(jLabel4))
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(27)
        							.addComponent(Phone, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(panel1, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE)))
        			.addGap(20)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(2)
        							.addComponent(jLabel5))
        						.addComponent(Mobile, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(4)
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(16)
        							.addComponent(jLabel6))
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(14)
        							.addComponent(Fax, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        				.addComponent(Save, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
        			.addGap(19)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(2)
        					.addComponent(jLabel7)
        					.addGap(22)
        					.addComponent(jLabel8))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(Email, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(Cancel, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addComponent(AltEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(12)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(Country, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel9))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(5)
        					.addComponent(jLabel10))
        				.addComponent(City, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(12)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(ZipCode, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel11))
        					.addGap(12)
        					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(StrNo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel13))
        					.addGap(17)
        					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(AppNo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel12))
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(StrName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel14)))
        				.addComponent(AddInfo, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE))
        			.addGap(22))
        );
        getContentPane().setLayout(groupLayout);

      

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddContact().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JButton Cancel;
    private javax.swing.JCheckBox Male;
    private javax.swing.JCheckBox Female;
    private JMenuItem Copy;
    private javax.swing.JComboBox Year;
    private javax.swing.JComboBox Month;
    private javax.swing.JComboBox Day;
    private javax.swing.JComboBox Country;
    private javax.swing.JComboBox City;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu View;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem AddContact;
    private javax.swing.JMenuItem SortA;
    private javax.swing.JMenuItem SortZ;
    private javax.swing.JMenuItem ZoomIn;
    private javax.swing.JMenuItem ZoomOut;
    private javax.swing.JMenuItem Mannul;
    private javax.swing.JMenuItem Video;
    private javax.swing.JMenuItem Version;
    private javax.swing.JMenuItem EditContact;
    private javax.swing.JMenuItem ManageContact;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem Undo;
    private javax.swing.JMenuItem Redo;
    private javax.swing.JMenuItem Cut;
    private javax.swing.JMenuItem Past;
    private javax.swing.JMenuItem Perference;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField ZipCode;
    private javax.swing.JTextField StrNo;
    private javax.swing.JTextField AppNo;
    private javax.swing.JTextField StrName;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField AddInfo;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Mobile;
    private javax.swing.JTextField Fax;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField AltEmail;
    private java.awt.Panel panel1;
   
    // End of variables declaration//GEN-END:variables
}