/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import java.awt.Component;
import javax.swing.JMenuItem;

/**
 *
 * @author Alizai
 */
public class AddressBook extends javax.swing.JFrame {

    /**
     * Creates new form SeProject2
     */
    public AddressBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SortList = new javax.swing.JComboBox();
        DeleteContact = new javax.swing.JButton();
        EditContact = new javax.swing.JButton();
        SearchContact = new javax.swing.JButton();
        ShowContact = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList();
        Search = new javax.swing.JTextField();
        AddContact = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        AddContacts = new javax.swing.JMenuItem();
        EditContacts = new javax.swing.JMenuItem();
        ManageContact = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        Undo = new javax.swing.JMenuItem();
        Redo = new javax.swing.JMenuItem();
        Copy = new JMenuItem();
        Cut = new javax.swing.JMenuItem();
        Past = new javax.swing.JMenuItem();
        Perference = new javax.swing.JMenuItem();
        View = new javax.swing.JMenu();
        SortA = new javax.swing.JMenuItem();
        SortZ = new javax.swing.JMenuItem();
        ZoomIn = new javax.swing.JMenuItem();
        ZoomOut = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        Mannul = new javax.swing.JMenuItem();
        Video = new javax.swing.JMenuItem();
        Version = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Address Book ");

        SortList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First Name ", "Last Name", "Date of Birth ", "Mobile Number" }));

        DeleteContact.setText("Delete Contact");
        DeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        EditContact.setText("Edit Contacs ");
        EditContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        SearchContact.setText("search Contact ");

        ShowContact.setText("Show Contact");
        ShowContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        List.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Last Name , First Name ", "Alizai ", "Bahiz ", "Sediqi ", "Ali", "Tanin", "Sulaiman khail", "Nasiri", "Alizai ", "Bahiz ", "Sediqi ", "Ali", "Tanin", "Sulaiman khail", "Nasiri", " ", "Alizai ", "Bahiz ", "Sediqi ", "Ali", "Tanin", "Sulaiman khail", "Nasiri", " ", "Alizai ", "Bahiz ", "Sediqi ", "Ali", "Tanin", "Sulaiman khail", "Nasiri", " ", " ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(List);

        Search.setText("Search Contact ");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        AddContact.setText("Add Contact");
        AddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        File.setText("File");

        AddContacts.setText("Add Contact ");
        File.add(AddContacts);

        EditContacts.setText("Edit Contact");
        File.add(EditContacts);

        ManageContact.setText("Manage Contacts ");
        File.add(ManageContact);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        File.add(Exit);

        MenuBar.add(File);

        Edit.setText("Edit");

        Undo.setText("Undo ");
        Edit.add(Undo);

        Redo.setText("redo");
        Edit.add(Redo);

        Copy.setSelected(true);
        Copy.setText("Copy ");
        Edit.add(Copy);

        Cut.setText("Cut");
        Edit.add(Cut);

        Past.setText("Past");
        Edit.add(Past);

        Perference.setText("Perference ");
        Edit.add(Perference);

        MenuBar.add(Edit);

        View.setText("View");

        SortA.setText("Sort A-Z");
        SortA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        View.add(SortA);

        SortZ.setText("Sort Z-A");
        View.add(SortZ);

        ZoomIn.setText("Zoom in +");
        View.add(ZoomIn);

        ZoomOut.setText("Zoom out -");
        View.add(ZoomOut);

        MenuBar.add(View);

        Help.setText("Help");

        Mannul.setText("Mannul ");
        Help.add(Mannul);

        Video.setText("Video Demo ");
        Help.add(Video);

        Version.setText("Version Info ");
        Help.add(Version);

        MenuBar.add(Help);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jScrollPane1)
        						.addComponent(SortList, 0, 230, Short.MAX_VALUE)
        						.addComponent(Search))
        					.addPreferredGap(ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(ShowContact, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
        						.addComponent(AddContact, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
        						.addComponent(EditContact, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
        						.addComponent(DeleteContact, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(0, 274, Short.MAX_VALUE)
        					.addComponent(SearchContact, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(SortList, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        				.addComponent(SearchContact, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(Search, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(AddContact, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(EditContact, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(DeleteContact, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(ShowContact, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(97, Short.MAX_VALUE))
        );
        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {DeleteContact, EditContact, SearchContact, ShowContact, AddContact});
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddressBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddressBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddressBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddressBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddressBook().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteContact;
    private javax.swing.JButton EditContact;
    private javax.swing.JButton SearchContact;
    private javax.swing.JButton ShowContact;
    private javax.swing.JButton AddContact;
    private JMenuItem Copy;
    private javax.swing.JComboBox SortList;
    private javax.swing.JList List;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu View;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem AddContacts;
    private javax.swing.JMenuItem SortA;
    private javax.swing.JMenuItem SortZ;
    private javax.swing.JMenuItem ZoomIn;
    private javax.swing.JMenuItem ZoomOut;
    private javax.swing.JMenuItem Mannul;
    private javax.swing.JMenuItem Video;
    private javax.swing.JMenuItem Version;
    private javax.swing.JMenuItem EditContacts;
    private javax.swing.JMenuItem ManageContact;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem Undo;
    private javax.swing.JMenuItem Redo;
    private javax.swing.JMenuItem Cut;
    private javax.swing.JMenuItem Past;
    private javax.swing.JMenuItem Perference;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField Search;
    // End of variables declaration//GEN-END:variables
}