/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JMenuItem;

/**
 *
 * @author Alizai
 */
public class Perference extends javax.swing.JFrame {

    /**
     * Creates new form SeProject5
     */
    public Perference() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        NewPassword = new javax.swing.JPasswordField();
        RNewPassword = new javax.swing.JPasswordField();
        OldPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ContColor = new java.awt.Choice();
        label1 = new java.awt.Label();
        FontSize = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        BackColor = new java.awt.Choice();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        FontType = new javax.swing.JComboBox();
        AppChanges = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Cancel.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		System.exit(0);
        	}
        });
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        AddContact = new javax.swing.JMenuItem();
        AddContact.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	
        		
        	}
        });
        EditContact = new javax.swing.JMenuItem();
        ManageContact = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Exit.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		System.exit(0);
        		
        	}
        });
        Edit = new javax.swing.JMenu();
        Undo = new javax.swing.JMenuItem();
        Redo = new javax.swing.JMenuItem();
        Copy = new JMenuItem();
        Cut = new javax.swing.JMenuItem();
        Past = new javax.swing.JMenuItem();
        Perference = new javax.swing.JMenuItem();
        View = new javax.swing.JMenu();
        SortA = new javax.swing.JMenuItem();
        SortZ = new javax.swing.JMenuItem();
        ZoomIn = new javax.swing.JMenuItem();
        ZoomOut = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        Mannul = new javax.swing.JMenuItem();
        Video = new javax.swing.JMenuItem();
        Version = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perference ");

        NewPassword.setText("jPasswordField1");

        RNewPassword.setText("jPasswordField2");

        OldPassword.setText("jPasswordField3");
        OldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Old Password ");

        jLabel2.setText("New Password ");

        jLabel3.setText("Re Enter New Password ");

        label1.setText("Font Color ");

        FontSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", " " }));

        jLabel4.setText("Font Size ");

        label2.setText("Back color ");

        label3.setText("Font type ");

        FontType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AppChanges.setText("Apply Changes ");

        Cancel.setText("Cancel");

        File.setText("File");

        AddContact.setText("Add Contact ");
        File.add(AddContact);

        EditContact.setText("Edit Contact");
        File.add(EditContact);

        ManageContact.setText("Manage Contacts ");
        File.add(ManageContact);

        Exit.setText("Exit");
        File.add(Exit);

        MenuBar.add(File);

        Edit.setText("Edit");

        Undo.setText("Undo ");
        Edit.add(Undo);

        Redo.setText("redo");
        Edit.add(Redo);

        Copy.setSelected(true);
        Copy.setText("Copy ");
        Edit.add(Copy);

        Cut.setText("Cut");
        Edit.add(Cut);

        Past.setText("Past");
        Edit.add(Past);

        Perference.setText("Perference ");
        Edit.add(Perference);

        MenuBar.add(Edit);

        View.setText("View");

        SortA.setText("Sort A-Z");
        SortA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        View.add(SortA);

        SortZ.setText("Sort Z-A");
        View.add(SortZ);

        ZoomIn.setText("Zoom in +");
        View.add(ZoomIn);

        ZoomOut.setText("Zoom out -");
        View.add(ZoomOut);

        MenuBar.add(View);

        Help.setText("Help");

        Mannul.setText("Mannul ");
        Help.add(Mannul);

        Video.setText("Video Demo ");
        Help.add(Video);

        Version.setText("Version Info ");
        Help.add(Version);

        MenuBar.add(Help);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(89)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(label1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel4))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(ContColor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(59)
        							.addComponent(label2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(BackColor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(FontSize, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(label3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(FontType, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabel1)
        						.addComponent(jLabel2)
        						.addComponent(jLabel3))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(NewPassword, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        								.addComponent(OldPassword, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(AppChanges, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(Cancel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        						.addComponent(RNewPassword, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))))
        			.addGap(0, 20, 20))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(57)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(AppChanges, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        				.addComponent(OldPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(20)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jLabel2)
        								.addComponent(NewPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addGap(22)
        							.addComponent(jLabel3))
        						.addComponent(RNewPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(ContColor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(label1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(FontSize, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel4)))
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(BackColor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(label2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(FontType, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(label3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        					.addGap(41))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(30)
        					.addComponent(Cancel)
        					.addContainerGap())))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Perference().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice ContColor;
    private java.awt.Choice BackColor;
    private javax.swing.JButton AppChanges;
    private javax.swing.JButton Cancel;
    private JMenuItem Copy;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JComboBox FontSize;
    private javax.swing.JComboBox FontType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu View;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem AddContact;
    private javax.swing.JMenuItem SortA;
    private javax.swing.JMenuItem SortZ;
    private javax.swing.JMenuItem ZoomIn;
    private javax.swing.JMenuItem ZoomOut;
    private javax.swing.JMenuItem Mannul;
    private javax.swing.JMenuItem Video;
    private javax.swing.JMenuItem Version;
    private javax.swing.JMenuItem EditContact;
    private javax.swing.JMenuItem ManageContact;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem Undo;
    private javax.swing.JMenuItem Redo;
    private javax.swing.JMenuItem Cut;
    private javax.swing.JMenuItem Past;
    private javax.swing.JMenuItem Perference;
    private javax.swing.JPasswordField NewPassword;
    private javax.swing.JPasswordField RNewPassword;
    private javax.swing.JPasswordField OldPassword;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}